### ISSUE TITLE
行为识别 error

### ISSUE THREAD

**Issue by huwade** [TianzhongSong/Real-Time-Action-Recognition#21]
Hi, when I use 行为识别, I got an error, below 

/home/wade/Desktop/Real-Time-Action-Recognition/utils/sort.py:37: RuntimeWarning: invalid value encountered in double_scalars
  r = w / float(h)
('trackers', array([[nan, nan, nan, nan,  1.]]))
Traceback (most recent call last):
  File "run.py", line 218, in show_camera
    xmin = int(d[0])
ValueError: cannot convert float NaN to integer
Aborted (core dumped)

Could you help, please

**Comment by sunfeng90** [comment]
To check the d[0].It may be a NaN.If it isn't a Nan, then convert it to the Integer type.
