### ISSUE TITLE
请问，如何将实时摄像头变成输入一段录像

### ISSUE THREAD

**Issue by xingyi-li** [TianzhongSong/Real-Time-Action-Recognition#23]

**Comment by xingyi-li** [comment]
解决了，虽然模型准确率不高，但是还是给出接解决办法
在run.py中找到并修改self.cap = cv2.VideoCapture('视频路径')，然后找到flag = self.cap.open(self.CAM_NUM)，将其注释，在下一行加上flag = True

**Comment by fxcdl** [comment]
@singngai 谢谢你的指导，但我面临以下的问题，我该怎么解决？
show = cv2.resize(frame, (settings.winWidth, settings.winHeight))
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by xingyi-li** [comment]
@fxcdl 就我目前遇到的这种错误的可能解决原因可能是你的录像路径写的不对，读不出来，你查查路径，试试绝对路径会不会有问题
