### ISSUE TITLE
训练结果

### ISSUE THREAD

**Issue by jacklala** [TianzhongSong/Real-Time-Action-Recognition#3]
能不能提供一下您现在的 weights_c3d_mask.h5和cnn_2d_crop.h5，所找的数据集有点不太行，如果可以的话请发到yaominggangde@163.com邮箱，谢谢

**Comment by yavana** [comment]
同问，如果可以请发送到281021244@qq.com邮箱，谢谢

**Comment by TianzhongSong** [comment]
@jacklala 已更新，权重文件在results文件夹下，由于训练数据太少，目前训练出来的模型几乎不能用

**Comment by TianzhongSong** [comment]
@yavana 已更新，权重文件在results文件夹下，由于训练数据太少，目前训练出来的模型几乎不能用

**Comment by yavana** [comment]
和作者在知乎私信了，终于中间报错搞定，终于跑起来了^_^
