### ISSUE TITLE
PyQt5 Error

### ISSUE THREAD

**Issue by akhilgupta0221** [TianzhongSong/Real-Time-Action-Recognition#8]
Hi

While compiling the program I am facing this below issue:

Traceback (most recent call last):
 File "run.py", line 3, in <module>
   from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

This issue is also reproducible with the simple QT application as well.
Can you please guide me here

Thanks in Advance !!!!!

Regards
Akhil

**Comment by TianzhongSong** [comment]
@akhilgupta0221 Using [Anaconda](https://www.anaconda.com/download/) is recommended. PyQt5 has been included in Anaconda.

**Comment by akhilgupta0221** [comment]
Thanks issue is solved So, closing it
